function Hd = FIR_Filter128FFT(Fs)
%FIR_FILTER128FFT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 23-Jun-2014 03:00:47

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 15360000;  % Sampling Frequency

Fpass = 472500;          % Passband Frequency
Fstop = 960000;        % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.1;             % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
