function Hd = FIR_Filter(Fs)
%FIR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 12-Jun-2014 19:17:18

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs = 30720000;  % Sampling Frequency

Fpass = 472500;  % Passband Frequency
Fstop = 547500;  % Stopband Frequency
Dpass = 0.1;     % Passband Ripple
Dstop = 0.1;     % Stopband Attenuation
dens  = 20;      % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
