function Hd = IIR_Filter(Fs)
%IIR FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 12-Jun-2014 18:54:51

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
% Fs = 30720000;  % Sampling Frequency

Fpass = 472500;  % Passband Frequency
Fstop = 547500;  % Stopband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 30;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);

Hd = sos(Hd);

% [EOF]
